before_install:
  - sudo apt-get install -y wget openssl libssl-dev coreutils
  - sudo apt-get install -y build-essential
  - wget -O openssl-1.0.2h.tar.gz https://www.openssl.org/source/openssl-1.0.2h.tar.gz
  - tar -xf openssl-1.0.2h.tar.gz
  - $(cd openssl-1.0.2h && ./config && make depend && make && sudo make install)
language: node_js
env:
  - CXX=g++-4.8
node_js:
  - '6.2'
  - '5.1'
  - '4.2'
  - '0.12'
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8


